services:
  prod:
    image: software-quality-with-cats:prod
    build:
      context: ./next
      dockerfile: Dockerfile
      target: prod
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - db

  dev:
    image: software-quality-with-cats:dev
    build:
      context: ./next
      dockerfile: Dockerfile
      target: dev
    environment:
      - NODE_ENV=development
    ports:
      - '3001:3000'
    volumes:
      - ./next:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
