import type { Metadata } from "next";

import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Software Quality With Cats",
  description: "Generated by Maximilian Gobbel",
};

/**
 * `RootLayout` is a layout component that wraps around other components and provides a consistent structure to your pages.
 * It sets the language of the page to English and applies the Inter font to the body of the page.
 * @param root0 - The props object.
 * @param root0.children - The child components to be rendered within this layout.
 * @returns The layout component with the child components.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
