# name: E2E Test

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   e2e-test:
#     name: E2E Test
#     timeout-minutes: 7
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: lts/*
#       - name: Set up environment variables
#         run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
#       - name: Install dependencies
#         working-directory: next
#         run: npm ci
#       - name: Execute build
#         working-directory: next
#         run: npm run build
#       - name: Install Playwright Browsers
#         working-directory: next
#         run: npx playwright install --with-deps
#       - name: Run Playwright tests
#         working-directory: next
#         run: npx playwright test
#       - uses: actions/upload-artifact@v4
#         if: always()
#         with:
#           name: playwright-report
#           path: next/playwright-report/
#           retention-days: 3

name: E2E Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Create .env.production file
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> ./next/.env.production
          echo API_KEY=${{ secrets.API_KEY }} >> ./next/.env.production
          echo API_URL=${{ secrets.API_URL }} >> ./next/.env.production
          echo FAVORITE_COUNT=${{ secrets.FAVORITE_COUNT }} >> ./next/.env.production

      - name: Create .env.local file
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> ./next/.env.local
          echo API_KEY=${{ secrets.API_KEY }} >> ./next/.env.local
          echo API_URL=${{ secrets.API_URL }} >> ./next/.env.local
          echo FAVORITE_COUNT=${{ secrets.FAVORITE_COUNT }} >> ./next/.env.local

      - name: Create .env file
        run: |
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> ./.env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> ./.env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> ./.env

      - name: Build and start Docker services
        run: docker-compose up -d

      - name: Change permissions
        run: sudo chmod -R 777 .
      - name: Install dependencies
        working-directory: next
        run: |
          npm config set prefix '~/.npm-global'
          npm ci

      - name: Install Playwright Browsers
        working-directory: next
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: next
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: next/playwright-report/
          retention-days: 3
