name: E2E Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: List Docker containers
        run: docker ps

      - name: Create .env.production file
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> ./next/.env.production
          echo API_KEY=${{ secrets.API_KEY }} >> ./next/.env.production
          echo API_URL=${{ secrets.API_URL }} >> ./next/.env.production
          echo FAVORITE_COUNT=${{ secrets.FAVORITE_COUNT }} >> ./next/.env.production

      - name: Create .env.local file
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> ./next/.env.local
          echo API_KEY=${{ secrets.API_KEY }} >> ./next/.env.local
          echo API_URL=${{ secrets.API_URL }} >> ./next/.env.local
          echo FAVORITE_COUNT=${{ secrets.FAVORITE_COUNT }} >> ./next/.env.local

      - name: Create .env file
        run: |
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> ./.env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> ./.env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> ./.env

      - name: Build and start Docker services
        run: docker-compose up -d prod

      - name: Change permissions
        run: sudo chmod -R 777 .
      - name: Install dependencies
        working-directory: next
        run: |
          npm config set prefix '~/.npm-global'
          npm ci

      - name: Run Api Tests
        working-directory: next
        run: npm run test:api

      - name: Install Playwright Browsers
        working-directory: next
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: next
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: next/playwright-report/
          retention-days: 3

      - name: Stop Docker services
        run: docker-compose down
