# name: E2E Test

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   e2e-test:
#     name: E2E Test
#     timeout-minutes: 7
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: lts/*
#       - name: Set up environment variables
#         run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
#       - name: Install dependencies
#         working-directory: next
#         run: npm ci
#       - name: Execute build
#         working-directory: next
#         run: npm run build
#       - name: Install Playwright Browsers
#         working-directory: next
#         run: npx playwright install --with-deps
#       - name: Run Playwright tests
#         working-directory: next
#         run: npx playwright test
#       - uses: actions/upload-artifact@v4
#         if: always()
#         with:
#           name: playwright-report
#           path: next/playwright-report/
#           retention-days: 3

name: E2E Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Build and start Docker services
        run: docker-compose up -d

      - name: Install dependencies
        working-directory: next
        run: npm ci

      - name: Run Playwright tests
        working-directory: next
        run: npm run test:e2e
