name: E2E Test

on:
  workflow_run:
    workflows: ['Build and Test']
    types:
      - completed

jobs:
  e2e-test:
    name: E2E Test
    timeout-minutes: 7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: next/.next/
      - name: Install dependencies
        working-directory: next
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: next
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: next
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: next/playwright-report/
          retention-days: 3
