name: performance test

on:
  push:
    branches: [dev]

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: List Docker containers
        run: docker ps

      - name: Create .env.production file
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> ./next/.env.production
          echo API_KEY=${{ secrets.API_KEY }} >> ./next/.env.production
          echo API_URL=${{ secrets.API_URL }} >> ./next/.env.production
          echo FAVORITE_COUNT=${{ secrets.FAVORITE_COUNT }} >> ./next/.env.production

      - name: Create .env.local file
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> ./next/.env.local
          echo API_KEY=${{ secrets.API_KEY }} >> ./next/.env.local
          echo API_URL=${{ secrets.API_URL }} >> ./next/.env.local
          echo FAVORITE_COUNT=${{ secrets.FAVORITE_COUNT }} >> ./next/.env.local

      - name: Create .env file
        run: |
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> ./.env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> ./.env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> ./.env

      - name: Build and start Docker services
        run: docker-compose up -d prod

      - name: Change permissions
        run: sudo chmod -R 777 .
      - name: Install dependencies
        working-directory: next
        run: |
          npm config set prefix '~/.npm-global'
          npm ci

      - name: Run Lighthouse Tests
        working-directory: next
        run: npm run test:performance

      - name: Stop Docker services
        run: docker-compose down
